name: wikibase_sdk
description: A reimplementation of 
version: 1.0.0
repository: https://github.com/lectrician1/wikibase_sdk

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
dependencies: 
  js: ^0.6.3
